export default {
  dismiss: 'Dismiss',
  account: 'button[id="navbarAccount"]',
  login: 'button[id="navbarLoginButton"]',
  email: 'input[name="email"]',
  password: 'input[name="password"]',
  submit: 'button[type="submit"]',
  plusIcon: 'svg[data-icon="plus-square"]',
  addToBasket: 'button[aria-label="Add to Basket"]',
  yourBasket: 'Your Basket',
  cart: 'span[class*="warn-notification"]',
  checkout: 'button[id="checkoutButton"]',
  addNewAddress: 'button[aria-label="Add a new address"]',
  country: 'input[data-placeholder="Please provide a country."]',
  name: 'input[data-placeholder="Please provide a name."]',
  phone: 'input[data-placeholder="Please provide a mobile number."]',
  zip: 'input[data-placeholder="Please provide a ZIP code."]',
  street: 'textarea[data-placeholder="Please provide an address."]',
  city: 'input[data-placeholder="Please provide a city."]',
  state: 'input[data-placeholder="Please provide a state."]',
  radio: 'label[class="mat-radio-label"]',
  continue: 'button[aria-label*="Proceed"]',
  addCard: 'Add a credit or debit card',
  cardInput: '[class*="mat-expansion-panel mat-elevation"] [class*=mat-input-element]',
  placeOrder: 'Place your order and pay',
  thankYou: 'Thank you for your purchase!',
  searchIcon: '[class*="mat-search_icon-search"]',
  search: 'input[id="mat-input-0"]',
  searchItemName: '[class="item-name"]',
  searchValue: 'span[id="searchValue"]',
  logout: 'button[id="navbarLogoutButton"]'
}